name: watch_movie_tv_show
description: "Flutter Video App - Stream & Download Offline"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ---------- State management ----------
  get: ^4.7.3

  # ---------- Network ----------
  dio: ^5.4.0

  # ---------- Storage ----------
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.5.3

  # ---------- Video Player ----------
  video_player: ^2.8.6
  chewie: ^1.8.1
  subtitle: ^0.1.4
  # translator: ^1.0.0
  google_mlkit_translation: ^0.13.0

  # ---------- Images ----------
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10

  # ---------- Download ----------
  background_downloader: ^8.4.1

  # ---------- UI/Utils ----------
  shimmer: ^3.0.0
  connectivity_plus: ^6.0.3
  logger: ^2.6.2
  intl: ^0.20.2
  url_launcher: ^6.1.10
  share_plus: ^12.0.1
  flutter_launcher_icons: ^0.14.3

  # ---------- Device & Permissions ----------
  device_info_plus: ^12.3.0
  package_info_plus: ^9.0.0
  screen_brightness: ^0.2.2+1

  # ---------- JSON Serialization ----------
  json_annotation: ^4.8.1

  # ---------- Local packages ----------
  exo_shared:
    git:
      url: git@github.com:trungs99/exo_shared.git
      ref: main
  wakelock_plus: ^1.4.0
  app_settings: ^7.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0
  flutter_flavorizr: ^2.4.1
  flutter_gen: 5.6.0
  flutter_gen_runner: 5.6.0

# Flavorizr
# dart run flutter_flavorizr -p android:buildGradle,android:androidManifest,google:firebase
flavorizr:
  flavors:
    dev:
      app:
        name: "(Dev) Watch Movie TV Show"
      android:
        applicationId: "com.watch.movie.tv.show.dev"
        resValues:
          ads_app_id:
            type: "string"
            value: "ca-app-pub-3940256099942544~3347511713"

    prod:
      app:
        name: "Watch Movie TV Show"
      android:
        applicationId: "com.watch.movie.tv.show"
        resValues:
          ads_app_id:
            type: "string"
            value: "ca-app-pub-3940256099942544~3347511713"
# Flutter Gen (disabled due to dependency conflict)
flutter_gen:
  output: lib/app/utils
  line_length: 100
  integrations:
    flutter_svg: true
# Flutter launcher icons
# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  remove_alpha_ios: false
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon_app.png"
  image_path: "assets/images/icon_app.png"
# Flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/ic_flags/
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
